# version is now using "compose spec"
# v2 and v3 are now combined!
# docker-compose v1.27+ required

services:
  fe:
    build: ./FE
    image: rujrawee11/fe:lastest
    ports: 
      - 8088:80
    links:
      - be
    networks:
      - front-tier
    

  be:
    build: ./BE
    image: rujrawee11/be:lastest
    ports: 
      - 3000:80
    networks:
      - back-tier
  
networks:
  front-tier:
  back-tier:
