services:
  fe:
    build: ./FE
    image: rujrawee11/fe:lastest
    ports:
      - "8088:80"
    container_name: fe

  be:
    build: ./BE
    image: rujrawee11/be:lastest
    ports:
      - "3000:80"
    container_name: be